@echo off
cd "Eventide-update"
copy "Eventide.3dsx" "../../Eventide-update/Eventide.3dsx"
copy "Eventide_demo.3dsx" "../../Eventide-update/Eventide_demo.3dsx"
copy "Eventide.cia" "../../Eventide-update/Eventide.cia"
copy "NTR_Launcher.nds" "../../Eventide-update/NTR_Launcher.nds"
copy "prev_ver" "../../Eventide-update/prev_ver"
copy "release-bootstrap" "../../Eventide-update/release-bootstrap"
copy "release-bootstrap.nds" "../../Eventide-update/release-bootstrap.nds"
copy "Eventide - TWLNAND side.cia" "../../Eventide-update/Eventide - TWLNAND side.cia"
copy "eventide.nds" "../../Eventide-update/eventide.nds"
copy "unofficial-bootstrap" "../../Eventide-update/unofficial-bootstrap"
copy "unofficial-bootstrap.nds" "../../Eventide-update/unofficial-bootstrap.nds"
copy "Eventide.smdh" "../../Eventide-update/Eventide.smdh"
pause
